baseurl = "/"
languageCode = "en-us"
title = "ESPM 288 Blogdown Demo"
theme = "hugo-now-ui"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Publications"
    url = "/pubs/"
    weight = 2
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3
[[menu.main]]
    name = "rayshader"
    url = "/rayshader/"
    weight = 4
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
    weight = 10
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"
    weight = 10

[params]
    description = "A website built through Hugo and blogdown."
    tint = "green"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

